import {IStory} from '../src'
export const mockRootFolders: IStory[] = [
  {
    content: {},
    default_root: null,
    is_folder: true,
    is_startpage: false,
    name: 'Folder 1',
    parent_id: 0,
    path: '/',
    pinned: false,
    slug: 'folder-1',
    tag_list: [],
  },
  {
    content: {},
    default_root: null,
    is_folder: true,
    is_startpage: false,
    name: 'Folder 2',
    parent_id: 0,
    path: '/',
    pinned: false,
    slug: 'folder-2',
    tag_list: [],
  },
  {
    content: {},
    default_root: null,
    is_folder: true,
    is_startpage: false,
    name: 'Folder 3',
    parent_id: 0,
    path: '/',
    pinned: false,
    slug: 'folder-3',
    tag_list: [],
  },
]
